import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';

export default function Archivednotes() {

    const [archiveArr, setArchiveArr] = useState([]);
    const [notes, setNotes] = useState([]);


    const route = useRouter();

    useEffect(() => {
        loginCheck();
        getArchives();
        getLocalNotes();
    }, []);

    function loginCheck() {
        const userName = sessionStorage.getItem('user');
        if (userName === '' || userName === null) {
            route.push('/profile');
        }
    }

    function getArchives() {
        const localArchiveArr = JSON.parse(localStorage.getItem('archiveNotes'));
        setArchiveArr(localArchiveArr);
    }

    function getLocalNotes() {
        const localNotesArr = JSON.parse(localStorage.getItem('localNotes'));
        if (localNotesArr !== '' || localNotesArr !== null) {
            setNotes(localNotesArr);
        }
    }

    function handleLogout() {
        sessionStorage.removeItem('user');
        route.push('/');
    }

    function handleUnarchive(noteId) {
        let unarchiveNote;
        for (let i = 0; i < archiveArr.length; i++) {
            if (archiveArr[i].id === noteId) {
                unarchiveNote = archiveArr.splice(i, 1);
                break;
            }
        }
        notes.push(unarchiveNote[0]);
        setNotes(notes);
        localStorage.setItem('localNotes', JSON.stringify(notes));
        setArchiveArr(archiveArr);
        localStorage.setItem('archiveNotes', JSON.stringify(archiveArr));
        route.replace('/profile/archivednotes');
    }

    return (
        <div>
            <Head>
                <title>Archieved Notes</title>
                <meta name="Simple Note App" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <div>
                    <nav className="navbar sticky-top bg-light" style={{ height: 70 }}>
                        <div className="container-fluid">
                            <h1 className="navbar-brand">Simple Note</h1>
                            <button type="button" class="btn btn-outline-dark" style={{ width: 90, marginRight: 20 }} onClick={handleLogout}>Log Out</button>
                        </div>
                    </nav>
                </div>


                <div style={{ marginLeft: 500, marginTop: 40 }}>
                    <h3 style={{ fontSize: 40 }}>Archieved Notes</h3>
                </div>

                <div className="row" style={{ marginLeft: 50, width: 1200, marginTop: 40 }}>
                    {
                        archiveArr.map((list) => {
                            return (
                                <>
                                    <div className="col-sm-4" style={{ marginTop: 15 }}>
                                        <div className="card" style={{ backgroundColor: "darkgreen" }}>
                                            <div className="card-body">
                                                <p className="card-text" style={{ color: "lightsalmon", fontSize: 15 }}>Created - {list.creationDate}</p>
                                                <h5 className="card-title" style={{ color: 'white' }}>{list.title}</h5>
                                                <p className="card-text" style={{ color: 'white' }}>{list.content}</p>
                                                <p className="card-text" style={{ color: "lightgrey", fontSize: 15 }}>Last updated on {list.updationDate}</p>
                                                <button type="button" class="btn btn-outline-warning" onClick={() => handleUnarchive(list.id)}>Unarchived</button>
                                            </div>
                                        </div>
                                    </div>
                                </>
                            )
                        })
                    }
                </div>
            </main>


        </div>
    )
}