import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router';
import { useEffect } from 'react';

export default function Home() {

  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');

  const route = useRouter();

  function handleClick() {

    if (username !== 'scribe') {
      alert("Enter Correct Username !");
    } else if (password !== 'scribe@1234') {
      alert("Enter Correct Password !");
    } else {
      sessionStorage.setItem('user', username);
      route.push('/profile');
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Simple Note App - Login page</title>
        <meta name="Simple Note App" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Simple <i className={styles.note}>Note</i>
        </h1>
        <p className={styles.noteps}>Get Started to Note </p>

        <div className={styles.accordion}>
          <div className="accordion" id="accordionExample">
            <div className="accordion-item">
              <h2 className="accordion-header" id="headingOne">
                <button className="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                  <span className={styles.loginbtn}> Login </span>
                </button>
              </h2>
              <div id="collapseTwo" class="accordion-collapse collapse show" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                <div className="accordion-body">
                  <div class="form-floating mb-2">
                    <input type="email" class="form-control" id="username" placeholder="Username" onChange={(event) => setUsername(event.target.value)} />
                    <label for="floatingInput">Username</label>
                  </div>
                  <div class="form-floating">
                    <input type="password" class="form-control" id="password" placeholder="Password" onChange={(event) => setPassword(event.target.value)} />
                    <label for="floatingPassword">Password</label>
                  </div>
                  <div className={styles.loginbtnclick}>
                    <button type="button" class="btn btn-outline-primary" onClick={handleClick}>Login</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </main >

    </div >
  )
}
